USE [dbAppExample]
GO

/****** Object:  Table [dbo].[TAB_OBJECT]    Script Date: 21/06/2022 10:51:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TAB_OBJECT](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[DESCRIPTION] [varchar](200) NULL,
	[TYPE_ID] [int] NOT NULL,
	[DATE_MODIFIED] [datetime] NOT NULL,
 CONSTRAINT [PK_TAB_OBJECT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TAB_OBJECT] ADD  CONSTRAINT [DF_TAB_OBJECT_DATE_MODIFIED]  DEFAULT (getdate()) FOR [DATE_MODIFIED]
GO

ALTER TABLE [dbo].[TAB_OBJECT]  WITH CHECK ADD  CONSTRAINT [FK_TAB_OBJECT_TAB_OBJECT] FOREIGN KEY([TYPE_ID])
REFERENCES [dbo].[TAB_TYPE] ([ID])
GO

ALTER TABLE [dbo].[TAB_OBJECT] CHECK CONSTRAINT [FK_TAB_OBJECT_TAB_OBJECT]
GO


