USE [dbAppExample]
GO

/****** Object:  Table [dbo].[TAB_TYPE]    Script Date: 21/06/2022 10:43:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TAB_TYPE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [varchar](100) NOT NULL,
	[DT_MODIFIED] [datetime] NOT NULL,
 CONSTRAINT [PK_TAB_TYPE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TAB_TYPE] ADD  CONSTRAINT [DF_TAB_TYPE_DT_MODIFIED]  DEFAULT (getdate()) FOR [DT_MODIFIED]
GO


