INSERT INTO TAB_TYPE ([DESCRIPTION]) VALUES ('Mobile');
GO

INSERT INTO TAB_TYPE ([DESCRIPTION]) VALUES ('NoteBook');
GO

INSERT INTO TAB_TYPE ([DESCRIPTION]) VALUES ('Mouse');
GO

INSERT INTO TAB_TYPE ([DESCRIPTION]) VALUES ('HeadPhone');
GO

INSERT INTO TAB_TYPE ([DESCRIPTION]) VALUES ('Windows');
GO

INSERT INTO TAB_TYPE ([DESCRIPTION]) VALUES ('Linux');
GO
