USE [dbAppExample]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		André Putz
-- Create date: 22/06/2022
-- Description:	Select all Objects related
-- =============================================
CREATE PROCEDURE [dbo].[PR_RELATIONS_API_SEL]	
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	SELECT TR.ID, 
		   TR.ID_OBJECT_A, TA.[NAME] AS NAME_A, TA.[DESCRIPTION] AS DESCRIPTION_A, TA.[TYPE_ID] AS TYPE_ID_A, TPA.[DESCRIPTION] AS TYPE_DESCRIPTION_A,
		   TR.ID_OBJECT_B, TB.[NAME] AS NAME_B, TB.[DESCRIPTION] AS DESCRIPTION_B, TB.[TYPE_ID] AS TYPE_ID_B, TPB.[DESCRIPTION] AS TYPE_DESCRIPTION_B
	FROM TAB_RELATIONS TR WITH(NOLOCK)
	INNER JOIN TAB_OBJECT TA WITH(NOLOCK) ON
		TR.ID_OBJECT_A = TA.ID
	INNER JOIN TAB_TYPE TPA WITH(NOLOCK) ON
		TA.TYPE_ID = TPA.ID
	INNER JOIN TAB_OBJECT TB WITH(NOLOCK) ON
		TR.ID_OBJECT_B = TB.ID
	INNER JOIN TAB_TYPE TPB WITH(NOLOCK) ON
		TB.TYPE_ID = TPB.ID
	ORDER BY
		TA.NAME ASC, TB.NAME ASC;
	
END
GO


