USE [dbAppExample]
GO

/****** Object:  Table [dbo].[TAB_RELATIONS]    Script Date: 21/06/2022 10:55:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TAB_RELATIONS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_OBJECT_A] [bigint] NOT NULL,
	[ID_OBJECT_B] [bigint] NOT NULL,
	[DATE_MODIFIED] [datetime] NOT NULL,
 CONSTRAINT [PK_TAB_RELATIONS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TAB_RELATIONS] ADD  CONSTRAINT [DF_TAB_RELATIONS_DATE_MODIFIED]  DEFAULT (getdate()) FOR [DATE_MODIFIED]
GO

ALTER TABLE [dbo].[TAB_RELATIONS]  WITH CHECK ADD  CONSTRAINT [FK_TAB_RELATIONS_TAB_OBJECT_A] FOREIGN KEY([ID_OBJECT_A])
REFERENCES [dbo].[TAB_OBJECT] ([ID])
GO

ALTER TABLE [dbo].[TAB_RELATIONS] CHECK CONSTRAINT [FK_TAB_RELATIONS_TAB_OBJECT_A]
GO

ALTER TABLE [dbo].[TAB_RELATIONS]  WITH CHECK ADD  CONSTRAINT [FK_TAB_RELATIONS_TAB_OBJECT_B] FOREIGN KEY([ID_OBJECT_B])
REFERENCES [dbo].[TAB_OBJECT] ([ID])
GO

ALTER TABLE [dbo].[TAB_RELATIONS] CHECK CONSTRAINT [FK_TAB_RELATIONS_TAB_OBJECT_B]
GO


